### ISSUE TITLE
Scrcpy2以上不支持

### ISSUE THREAD

**Issue by 158323479** [DawningW/swy-bot#2]
Scrcpy2以上的包放入执行之后 Scrcpy-server会报连接不上服务 大佬知道是什么原因吗 其他基本都一致 就改了2.0之后的参数格式

**Comment by DawningW** [comment]
2.0可能有一些别的改动吧, 我有时间研究一下, 最近太忙了(

**Comment by 158323479** [comment]
投屏这块我解决了 启动方式变了导致对接不上 如果你需要我可以提供给你 不过操作那块我没有使用场景 没看

**Comment by DawningW** [comment]
最新提交已支持 Scrcpy 2.1.1
要改的地方还挺多的, 不只是启动参数, 具体改动请见 [`3921afb08e7f1e7e625852ee9a8b69430ba6ee27...e8ff1fddc5fcac5ed688536a8a366622155920bd`](https://github.com/DawningW/swy-bot/compare/3921afb08e7f1e7e625852ee9a8b69430ba6ee27...e8ff1fddc5fcac5ed688536a8a366622155920bd#diff-83b89b9a132f9c6f2d65fa6f2cd73b79c6a266ac348b30ec21f285c92ec0e3a2)
